// service/ema/src/lib/comp/Nomination.svelte
<script lang="ts">
  import { subNamesOfWork, type Work } from '$lib/domain/entity';
  export let work: Work;
</script>

<div class="flex flex-col items-start px-4 py-2 bg-overlay rounded">
  <p class="flex-1 font-serif text-2xl">{work.name}</p>
  {#each subNamesOfWork(work) as name (name)}
    <p class="text-subtle">{name}</p>
  {/each}
</div>

// mediavote/frontend/src/app/2022/nomination/[index]/Nomination.tsx
interface NominationProps {
  name: string;
  alias: string[];
  className?: string;
}

export default function Nomination({
  name,
  alias,
  className,
}: NominationProps) {
  return (
    <div
      className={`flex flex-col wide:flex-row items-start wide:items-center px-4 py-2 bg-overlay rounded ${className}`}
    >
      <p className="flex-1 font-serif text-2xl">{name}</p>
      <div className="flex-1">
        {alias.map((a) => (
          <p className="text-subtle" key={a}>
            {a}
          </p>
        ))}
      </div>
    </div>
  );
}
