// service/ema/src/lib/comp/Button.svelte
<script lang="ts">
  type Variant = 'primary' | 'secondary' | 'negative' | 'disable';
  export let variant: Variant = 'primary';
  export let type: 'submit' | 'button' = 'button';
</script>

<button
  class="w-full h-10 px-8 rounded text-base"
  class:bg-pine={variant === 'primary'}
  class:bg-love={variant === 'secondary'}
  class:bg-gold={variant === 'negative'}
  class:bg-muted={variant === 'disable'}
  disabled={variant === 'disable'}
  {type}
>
  <slot />
</button>

// mediavote-web/src/app/shared/Button.tsx
'use client';

import { useButton } from 'react-aria';
import { ReactNode, useRef } from 'react';

interface ButtonProps {
  className?: string;
  children?: ReactNode;
  disabled?: boolean;
  variant: 'primary' | 'secondary' | 'negative';
  type: 'submit' | 'reset' | 'button';
  onClick?: (e: Event) => void;
}

export default function Button(props: ButtonProps) {
  let ref = useRef<HTMLButtonElement>(null);
  let { buttonProps } = useButton(props, ref);
  const { className, children, disabled, variant, type } = props;
  let bg;
  if (disabled) {
    bg = 'bg-muted';
  } else if (variant === 'secondary') {
    bg = 'bg-love';
  } else if (variant === 'negative') {
    bg = 'bg-gold';
  } else {
    bg = 'bg-pine';
  }

  return (
    <button
      {...buttonProps}
      ref={ref}
      className={`${bg} text-base w-full px-8 h-10 rounded ${className || ''}`}
      disabled={disabled}
      type={type}
    >
      {children}
    </button>
  );
}
